# Using the official Node.js image as the base image
FROM node:21-bullseye

# Create and set the working directory
WORKDIR /moviebait

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Install Playwright and its dependencies
RUN npx playwright install --with-deps chromium

# Copy the entire project to the working directory
COPY . .

# Run the tests as defined in package.json
# CMD ["npm", "run", "ci"]