name: Frontend CI and Deploy

on:
  push:
    branches:
      - 'release/**'  # Trigger on push to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Build Docker image for test
      run: docker build -f dockerfile.test -t moviebait:test .

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -f dockerfile.prod -t moviebait:latest .

    - name: Deploy to Server
      run: docker run -p 5173:5173 moviebait:latest
